import { DestinationItem } from '@/types';

export const DESTINATIONS_DATA: DestinationItem[] = [
  // Quintana Roo
  {
    id: 'cancun-hotel-zone',
    slug: 'cancun-zona-hotelera',
    name: 'Cancún (Zona Hotelera)',
    region: 'quintana_roo',
    regionLabel: 'Quintana Roo',
    tagline: 'Playas azul turquesa de ensueño y resorts de clase mundial',
    description: 'Traslado express y sin escalas a cualquier resort sobre el Boulevard Kukulcán (Km 1 a Punta Nizuc). Disfruta de la mejor arena blanca de México.',
    estimatedDuration: '20 - 30 min',
    distanceKm: 22,
    pricePerPersonUsd: 15,
    priceGroupVanUsd: 45,
    priceVipUsd: 95,
    popular: true,
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85',
    features: ['Monitoreo de vuelo en vivo', 'Sin esperas en terminal', 'Bebidas de cortesía VIP']
  },
  {
    id: 'playa-del-carmen',
    slug: 'playa-del-carmen',
    name: 'Playa del Carmen',
    region: 'quintana_roo',
    regionLabel: 'Quintana Roo',
    tagline: 'Quinta Avenida, clubes de playa y ambiente cosmopolita',
    description: 'Servicio directo a Playacar, Centro y resorts de la Riviera Maya con operadores bilingües certificados y máximo confort.',
    estimatedDuration: '45 - 55 min',
    distanceKm: 55,
    pricePerPersonUsd: 25,
    priceGroupVanUsd: 75,
    priceVipUsd: 145,
    popular: true,
    imageUrl: 'https://images.unsplash.com/photo-1512813195386-6cf811ad3542?auto=format&fit=crop&w=1200&q=85',
    features: ['Parada opcional en tiendas', 'Aire acondicionado premium', 'Wifi de alta velocidad']
  },
  {
    id: 'tulum',
    slug: 'tulum',
    name: 'Tulum & Zona Hotelera',
    region: 'quintana_roo',
    regionLabel: 'Quintana Roo',
    tagline: 'Misticismo maya sobre el acantilado y selva bohemia',
    description: 'Conexión desde el Aeropuerto de Cancún a Tulum Pueblo, Zona Hotelera costera o Aldea Zamá sin complicaciones ni retrasos.',
    estimatedDuration: '90 - 110 min',
    distanceKm: 128,
    pricePerPersonUsd: 45,
    priceGroupVanUsd: 135,
    priceVipUsd: 240,
    popular: true,
    imageUrl: 'https://images.unsplash.com/photo-1519451241324-20b4ea2c422a?auto=format&fit=crop&w=1200&q=85',
    features: ['Toallitas refrescantes', 'Conductores locales expertos', 'Seguro de viajero ampliado']
  },
  {
    id: 'akumal',
    slug: 'akumal',
    name: 'Akumal',
    region: 'quintana_roo',
    regionLabel: 'Quintana Roo',
    tagline: 'Santuario natural de tortugas marinas y aguas calmas',
    description: 'Traslados a la bahía de Akumal y resorts de media luna con confort absoluto, puntualidad y operadores amigables.',
    estimatedDuration: '75 min',
    distanceKm: 92,
    pricePerPersonUsd: 35,
    priceGroupVanUsd: 95,
    priceVipUsd: 185,
    popular: false,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=85',
    features: ['Asientos reclinables', 'Espacio extra para maletas', 'Agua embotellada fría']
  },
  {
    id: 'puerto-morelos',
    slug: 'puerto-morelos',
    name: 'Puerto Morelos',
    region: 'quintana_roo',
    regionLabel: 'Quintana Roo',
    tagline: 'Pueblo pesquero auténtico y el faro inclinado legendario',
    description: 'A solo 20 minutos del aeropuerto de Cancún, ideal para estancias relajantes, snorkel en arrecife y ambiente náutico.',
    estimatedDuration: '20 - 25 min',
    distanceKm: 26,
    pricePerPersonUsd: 18,
    priceGroupVanUsd: 50,
    priceVipUsd: 105,
    popular: false,
    imageUrl: 'https://images.unsplash.com/photo-1533743914085-403451366d53?auto=format&fit=crop&w=1200&q=85',
    features: ['Llegada inmediata', 'Atención personalizada', 'Asistencia de equipaje']
  },
  {
    id: 'holbox',
    slug: 'holbox-chiquila',
    name: 'Holbox (Puerto de Chiquilá)',
    region: 'quintana_roo',
    regionLabel: 'Quintana Roo',
    tagline: 'Bancos de arena virgen, bioluminiscencia y flamingos',
    description: 'Traslado terrestre seguro y climatizado directo al muelle de ferris en Chiquilá con coordinación de cruces y maletas.',
    estimatedDuration: '120 min',
    distanceKm: 140,
    pricePerPersonUsd: 55,
    priceGroupVanUsd: 165,
    priceVipUsd: 280,
    popular: true,
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85',
    features: ['Coordinación con ferris', 'Unidades de última generación', 'Ruta panorámica']
  },
  {
    id: 'bacalar',
    slug: 'bacalar',
    name: 'Bacalar (Laguna de los 7 Colores)',
    region: 'quintana_roo',
    regionLabel: 'Quintana Roo',
    tagline: 'Aguas cristalinas con infinitos tonos de azul y cenotes',
    description: 'Servicio privado de larga distancia con paradas de descanso programadas, snack pack y máxima comodidad en camionetas ejecutivas.',
    estimatedDuration: '4 horas',
    distanceKm: 345,
    pricePerPersonUsd: 90,
    priceGroupVanUsd: 290,
    priceVipUsd: 490,
    popular: false,
    imageUrl: 'https://images.unsplash.com/photo-1613224327093-bcc6c035d4c1?auto=format&fit=crop&w=1200&q=85',
    features: ['Servicio de chofer dedicado', 'Paradas flexibles a petición', 'Snacks y bebidas frías']
  },

  // Yucatán
  {
    id: 'chichen-itza',
    slug: 'chichen-itza',
    name: 'Chichén Itzá',
    region: 'yucatan',
    regionLabel: 'Yucatán',
    tagline: 'Maravilla del Mundo Moderno y Pirámide de Kukulkán',
    description: 'Tour privado o traslado redondo temprano para llegar antes de las multitudes y admirar el descenso de la serpiente emplumada.',
    estimatedDuration: '2 horas 15 min',
    distanceKm: 200,
    pricePerPersonUsd: 60,
    priceGroupVanUsd: 210,
    priceVipUsd: 350,
    popular: true,
    imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&w=1200&q=85',
    features: ['Entrada prioritaria sugerida', 'Tiempo de espera incluido', 'Guía bilingüe opcional']
  },
  {
    id: 'valladolid',
    slug: 'valladolid',
    name: 'Valladolid (Pueblo Mágico)',
    region: 'yucatan',
    regionLabel: 'Yucatán',
    tagline: 'Arquitectura virreinal, cenotes urbanos y gastronomía maya',
    description: 'Traslado cultural cómodo con parada recomendada en el Cenote Zací y degustación tradicional de marquesitas y cochinita pibil.',
    estimatedDuration: '1 hora 50 min',
    distanceKm: 160,
    pricePerPersonUsd: 48,
    priceGroupVanUsd: 175,
    priceVipUsd: 295,
    popular: false,
    imageUrl: 'https://images.unsplash.com/photo-1676517308564-42b45298ddf2?auto=format&fit=crop&w=1200&q=85',
    features: ['Parada en centro histórico', 'Climatización dual', 'Conductor bilingüe']
  },
  {
    id: 'merida',
    slug: 'merida',
    name: 'Mérida (La Ciudad Blanca)',
    region: 'yucatan',
    regionLabel: 'Yucatán',
    tagline: 'Paseo de Montejo, serenatas coloniales y seguridad total',
    description: 'Conexión ejecutiva interurbana directa entre Cancún / Riviera Maya y la capital yucateca con autopista de cuota incluida.',
    estimatedDuration: '3 horas 30 min',
    distanceKm: 310,
    pricePerPersonUsd: 80,
    priceGroupVanUsd: 260,
    priceVipUsd: 440,
    popular: false,
    imageUrl: 'https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?auto=format&fit=crop&w=1200&q=85',
    features: ['Autopista de cuota incluida', 'Cargadores para dispositivos', 'Máxima seguridad vial']
  },
  {
    id: 'izamal',
    slug: 'izamal',
    name: 'Izamal (Ciudad de las Tres Culturas)',
    region: 'yucatan',
    regionLabel: 'Yucatán',
    tagline: 'Fascinantes fachadas amarillas y el Convento de San Antonio',
    description: 'Paseo exclusivo por las calles pintadas de amarillo ocre con pirámides mayas prehispánicas en pleno centro urbano.',
    estimatedDuration: '2 horas 45 min',
    distanceKm: 250,
    pricePerPersonUsd: 65,
    priceGroupVanUsd: 220,
    priceVipUsd: 370,
    popular: false,
    imageUrl: 'https://images.unsplash.com/photo-1728378498552-344bc051e793?auto=format&fit=crop&w=1200&q=85',
    features: ['Itinerario flexible', 'Hielera con bebidas', 'Atención premium']
  },
  {
    id: 'ruta-cenotes',
    slug: 'ruta-de-cenotes',
    name: 'Ruta de Cenotes (Puerto Morelos)',
    region: 'yucatan',
    regionLabel: 'Yucatán & Selva',
    tagline: 'Cavernas subterráneas, tirolesas y aguas sagradas mayas',
    description: 'Circuito privado por los cenotes más espectaculares: Verde Lucero, Boca del Puma, Kin-Ha y La Noria con aguas color jade.',
    estimatedDuration: '40 min (inicio)',
    distanceKm: 42,
    pricePerPersonUsd: 32,
    priceGroupVanUsd: 110,
    priceVipUsd: 195,
    popular: true,
    imageUrl: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=85',
    features: ['Espera durante tu baño en cenote', 'Toallas limpias a bordo', 'Ruta 100% personalizada']
  },

  // Parques y Aventura
  {
    id: 'xcaret',
    slug: 'parque-xcaret',
    name: 'Parque Xcaret',
    region: 'parques',
    regionLabel: 'Parques y Aventura',
    tagline: 'El majestuoso paraíso de México y el show México Espectacular',
    description: 'Llega descansado y regresa de noche tras el show con transporte privado exclusivo esperándote justo en la puerta principal.',
    estimatedDuration: '60 min',
    distanceKm: 65,
    pricePerPersonUsd: 28,
    priceGroupVanUsd: 85,
    priceVipUsd: 160,
    popular: true,
    imageUrl: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=85',
    features: ['Salida flexible tras el show', 'Coordinación con tu boleto', 'Aire acondicionado garantizado']
  },
  {
    id: 'xel-ha',
    slug: 'parque-xel-ha',
    name: 'Parque Xel-Há',
    region: 'parques',
    regionLabel: 'Parques y Aventura',
    tagline: 'El acuario natural más impresionante del Caribe con todo incluido',
    description: 'Viaje cómodo en familia o grupo para disfrutar de snorkel ilimitado con peces multicolores, caletas y el gran faro mirador.',
    estimatedDuration: '80 min',
    distanceKm: 110,
    pricePerPersonUsd: 36,
    priceGroupVanUsd: 115,
    priceVipUsd: 210,
    popular: true,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=85',
    features: ['Espacio para toallas y equipo', 'Chofer puntual a la hora de cierre', 'Agua fresca']
  },
  {
    id: 'xplor',
    slug: 'parque-xplor',
    name: 'Parque Xplor & Xplor Fuego',
    region: 'parques',
    regionLabel: 'Parques y Aventura',
    tagline: 'Adrenalina pura, tirolesas sobre la selva y vehículos anfibios',
    description: 'Servicio ideal tanto de día como de noche para vivir la experiencia Xplor Fuego entre antorchas con total tranquilidad.',
    estimatedDuration: '55 min',
    distanceKm: 62,
    pricePerPersonUsd: 28,
    priceGroupVanUsd: 85,
    priceVipUsd: 160,
    popular: true,
    imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&w=1200&q=85',
    features: ['Regreso nocturno seguro', 'Atención directa en taquilla', 'Unidades limpias y desinfectadas']
  }
];

export const AIRPORT_ORIGINS = [
  { id: 'CUN_T2', name: 'Aeropuerto Cancún - Terminal 2 (Nacional & Charter)', code: 'CUN' },
  { id: 'CUN_T3', name: 'Aeropuerto Cancún - Terminal 3 (Vuelos Internacionales)', code: 'CUN' },
  { id: 'CUN_T4', name: 'Aeropuerto Cancún - Terminal 4 (Nuevas Aerolíneas Internacionales)', code: 'CUN' },
  { id: 'CUN_GEN', name: 'Aeropuerto Cancún - Llegadas Generales (Cualquier Terminal)', code: 'CUN' },
];

export const HOTEL_HOTEL_ZONES = [
  'Cancún Zona Hotelera',
  'Cancún Centro / Downtown',
  'Puerto Juárez / Ferry a Isla Mujeres',
  'Playa Mujeres / Costa Mujeres',
  'Puerto Morelos',
  'Playa del Carmen Centro / Playacar',
  'Riviera Maya Norte (Mayakoba)',
  'Puerto Aventuras',
  'Akumal',
  'Tulum Pueblo',
  'Tulum Zona Hotelera'
];
