services:
  # Servicio Web Único 100% Gratuito en Render (Free Tier)
  - type: web
    name: americancun-transfer
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://americancun-transfer.onrender.com
      - key: NEXT_PUBLIC_BANK_NAME
        value: BBVA México
      - key: NEXT_PUBLIC_BANK_BENEFICIARY
        value: Americancun Transfer S.A. de C.V.
      - key: NEXT_PUBLIC_BANK_CLABE
        value: "012691001234567890"
      - key: NEXT_PUBLIC_SUPPORT_WHATSAPP
        value: "+529981234567"
      - key: WORKER_SECRET_KEY
        value: americancun_free_token_2026
